### PR TITLE
Mock bookmark state related communication between the browser frontend and the server

### PR DESCRIPTION
**Pull request by victorporof**
Fixes https://github.com/victorporof/tofino/issues/55

Signed-off-by: Victor Porof <victor.porof@gmail.com>

### CODE REVIEW

**Review by bgrins — COMMENTED** [review]
Do we want to keep 'toggled' semantics?  IIRC this was pushed back against in tofino in favor of explicitly passing the current value so that it could be traced through logs / not get confused between frontends and server.  If we want to go that route I'd be happy to keep the 'toggled' name but include true/false in the payload.

**Comment by victorporof** [comment]
The point of using "toggle" is to avoid sending over any explicit "starred" state from the frontend, since the frontend isn't the source of truth for "starredness". With the flow described in #55, it's up to the server to decide what to do with the "starring" action event, and inform the frontend about what the state should end up being. I don't see any value in passing in what "the frontend thinks the starred state is at this particular time". Strong opinion weakly held.

**Comment by bgrins** [comment]
The discussion was in the inline comments here: https://github.com/mozilla/tofino/pull/90.  I guess in that case it was about frontend only state and I see your point about the server controlling the setting. I still think it's relevant though that the frontend set it to true or false - for example given this case:

* 2 windows opened on the same URL (not starred)
* Both set starred = true at the same-ish time

It's relevant that both thought they were setting the star to true.  Even though the server is the source of truth it can take that info and decide that the end result should be 'true'.  If only 'toggle' is passed we'd end up with the page unstarred.

**Comment by victorporof** [comment]
Ok, I'll switch from TOGGLE to STAR/UNSTAR, maybe it make sense in this case. We'll have to keep this in mind and adjust accordingly in the future as we see fit.

**Comment by bgrins** [comment]
> Ok, I'll switch from TOGGLE to STAR/UNSTAR, maybe it make sense in this case. We'll have to keep this in mind and adjust accordingly in the future as we see fit.

I'd slightly prefer to keep one action with a payload just because it's less boilerplate but also weakly held.

**Comment by victorporof** [comment]
@bgrins updated.

**Review by bgrins — APPROVED** [review]

**Comment by victorporof** [comment]
Rebased.

**Comment by victorporof** [comment]
This depends on https://github.com/victorporof/tofino/pull/71 which awaits review.

**Pull request closed without merging**
