### PR TITLE
Mock history state related communication between the browser frontend and the server

### PR DESCRIPTION
**Pull request by victorporof**
Fixes https://github.com/victorporof/tofino/issues/54

### CODE REVIEW

**Review by bgrins — APPROVED** [review]
This all seems reasonable.  One thing I notice: when `npm run qbrt+logging` I don't see the "BROWSER SERVER Visited" logs in output - maybe we haven't hooked up the correct mozbrowser events to trigger the action.  Would you be able to check into that and make sure we are getting similar behavior here, or in a follow up?

**Comment by victorporof** [comment]
This is due to the fact that `IframeMozBrowser` (used in qbrt) doesn't yet expose all the necessary events for page navigations. Here's the list of all expected events: https://github.com/victorporof/tofino/blob/bfg-browser/src/shared/widgets/web-contents/index.jsx#L64

Here's how we surface those events in electron's equivalent `WebView` component: https://github.com/victorporof/tofino/blob/bfg-browser/src/shared/widgets/web-contents/webview.jsx#L22

**Comment by bgrins** [comment]
Some relevant mozbrowser->webview mappings are here: https://github.com/mozilla/positron/pull/60/files#diff-64cfcf66b868bbadee651a97e11bd194R275.  We'll need to figure out individual mappings case-by-case, ideally when landing features that rely on them so we can keep qbrt as a first-class runner

**Comment by victorporof** [comment]
Rebased.

**Comment by victorporof** [comment]
This depends on https://github.com/victorporof/tofino/pull/71 which awaits review.

**Pull request closed without merging**
